@startuml
object gameSession {
id = 0002
isOver = false
points = 20
}

object map {
size = (4,4)
horizontalBorderCrossable = true
verticalBorderCrossable = true
fruitsReappear = false
}

object emptyTile1 {
position = (0,0)
}

object emptyTile2 {
position = (0,1)
}

object emptyTile3 {
position = (0,2)
}

object emptyTile4 {
position = (0,3)
}

object fruit1 {
position = (1,0)
points = 10
}

object emptyTile5 {
position = (1,1)
}

object fruit2 {
position = (1,2)
points = 10
}

object wall1 {
position = (1,3)
canMove = false
}

object wall2 {
position = (2,0)
canMove = false
}

object wall3 {
position = (2,1)
canMove = false
}

object pacmanPlayer {
position = (2,2)
isAlive = false
}

object wall4 {
position = (2,3)
canMove = false
}

object emptyTile6 {
position = (3,0)
}

object movingEnemy1 {
position = (3,1)
canMove = true
}

object emptyTile7 {
position = (3,2)
}

object emptyTile8 {
position = (3,3)
}


gameSession --> map
map o-- emptyTile1
map o-- emptyTile2
map o-- emptyTile3
map o-- emptyTile4
map o-- emptyTile5
map o-- emptyTile6
map o-- emptyTile7
map o-- emptyTile8
map o-- fruit1
map o-- fruit2
map o-- wall1
map o-- wall2
map o-- wall3
map o-- wall4
map o-- pacmanPlayer
map o-- movingEnemy1


@enduml