@startuml
object gameSession {
id = 0001
isOver = false
points = 10
}

object map {
size = (4,4)
horizontalBorderCrossable = true
verticalBorderCrossable = false
fruitsReappear = true
}

object fruit1 {
position = (0,0)
points = 10
}

object emptyTile1 {
position = (0,1)
}

object snakeBody1 {
position = (0,2)
canMove = true
}

object emptyTile2 {
position = (0,3)
}

object emptyTile3 {
position = (1,0)
}

object emptyTile4 {
position = (1,1)
}

object snakeBody2 {
position = (1,2)
canMove = true
}

object emptyTile5 {
position = (1,3)
}

object emptyTile6 {
position = (2,0)
}

object snakePlayer {
position = (2,1)
isAlive = true
size = 4
}

object snakeBody3 {
position = (2,2)
canMove = true
}

object emptyTile7 {
position = (2,3)
}

object emptyTile8 {
position = (3,0)
}

object emptyTile9 {
position = (3,1)
}

object emptyTile10 {
position = (3,2)
}

object emptyTile11 {
position = (3,3)
}

gameSession --> map
map o-- emptyTile1
map o-- emptyTile2
map o-- emptyTile3
map o-- emptyTile4
map o-- emptyTile5
map o-- emptyTile6
map o-- emptyTile7
map o-- emptyTile8
map o-- emptyTile9
map o-- emptyTile10
map o-- emptyTile11
map o-- fruit1
map o-- snakeBody1
map o-- snakeBody2
map o-- snakeBody3
map o-- snakePlayer

snakePlayer <-- snakeBody3
snakeBody3 <-- snakeBody2
snakeBody2 <-- snakeBody1


@enduml